version: '3.8'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./content:/var/www/html
      - ./etc/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:8080"
